// Writes Trommi/Core/DoodleTables.swift: the points of the named drawings (NAMED), the
// sketched icons (SKETCH) and the crown (CROWN) of client/web/js/ui.js, so the Swift
// port draws from the same numbers as the web. ui.js does not export these tables, so
// they are read out of its source text.   node client/ios/tools/doodle-tables.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const source = fs.readFileSync(path.join(here, '..', '..', 'web', 'js', 'ui.js'), 'utf8')

// One top-level statement of ui.js: from its first line to the first line that closes it at column 0.
function statement(start, end) {
  const from = source.indexOf(start)
  if (from < 0) throw new Error(`ui.js has no "${start}"`)
  const to = source.indexOf(end, from)
  if (to < 0) throw new Error(`"${start}" does not end with "${end.trim()}"`)
  return source.slice(from, to + end.length)
}
const code = [
  statement('const straight = ', '\n'),
  statement('const NAMED = {', '\n}\n'),
  statement('const KINDS = ', '\n'),
  statement('const CROWN = ', '\n'),
  statement('const flip = ', '\n'),
  statement('const THUMB = [', '\n]\n'),
  statement('const SKETCH = {', '\n}\n'),
].join('\n')
const { NAMED, KINDS, CROWN, SKETCH } = new Function(`${code}\nreturn { NAMED, KINDS, CROWN, SKETCH }`)()

const num = v => String(Number(v.toFixed(4)))
const flat = points => points.map(([x, y]) => `${num(x)}, ${num(y)}`).join(', ')
const name = text => JSON.stringify(text)

const crown = CROWN.split(/\s+(?=[ML])/).map(part => {
  const [x, y] = part.slice(1).trim().split(/\s+/).map(Number)
  return `.${part[0] === 'M' ? 'move' : 'line'}(${num(x)}, ${num(y)})`
})

const out = `// Generated by tools/doodle-tables.mjs from client/web/js/ui.js (NAMED, KINDS, SKETCH, CROWN).
// Do not edit by hand: run the tool again; CI checks that this file is what it writes.
import Foundation

enum DoodleTables {
    /// One stroke of the pen: x, y, x, y, ... A straight stroke keeps its corners.
    struct Stroke: Equatable, Sendable {
        var straight: Bool
        var xy: [Double]
    }

    /// The eight generated kinds, in the order of DOODLES.
    static let kinds: [String] = [${KINDS.map(name).join(', ')}]

    /// The named drawings, in the order the web offers them.
    static let namedOrder: [String] = [${Object.keys(NAMED).map(name).join(', ')}]

    /// Points in the 32 box.
    static let named: [String: [Stroke]] = [
${Object.entries(NAMED).map(([key, strokes]) => `        ${name(key)}: [\n${strokes.map(s => `            Stroke(straight: ${Boolean(s.straight)}, xy: [${flat(s)}]),`).join('\n')}\n        ],`).join('\n')}
    ]

    /// The sketched icons: points in the 24 box, one list per stroke.
    static let sketch: [String: [[Double]]] = [
${Object.entries(SKETCH).map(([key, strokes]) => `        ${name(key)}: [\n${strokes.map(s => `            [${flat(s)}],`).join('\n')}\n        ],`).join('\n')}
    ]

    /// The crown of a starred session, in a box of 26 x 19.
    static let crown: [PathCommand] = [${crown.join(', ')}]
}
`
const file = path.join(here, '..', 'Trommi', 'Core', 'DoodleTables.swift')
fs.writeFileSync(file, out)
console.log(`${Object.keys(NAMED).length} named drawings, ${Object.keys(SKETCH).length} sketches -> ${file}`)
