// Every screen the board can show: the list behind /screens.html (js/screens-page.js draws it) and
// docs/screens.md. A debug index: views, states, sheets and notes, with how each is reached and whether it is
// in use (current), alive behind a switch nobody sees (hidden), or code that can no longer be reached (dead).
//
// One entry: { area, name, desc, status, to, steps?, where?, popup?, at?, needs? }
//   to      the address that opens it: a string, or a function of what the board holds right now (liveOf)
//           that returns null when there is nothing to show it with; left out when no address reaches it
//   steps   what to do where an address is not enough
//   where   the file (and line, as of the day it was written) that mounts it
//   popup   set when it lies over the page: 'page' (fills the screen, has an address), 'anchored' (a small
//           sheet or menu at what was pressed, no veil), 'modal' (blocks the page), 'note' (passes by itself)
//   at      'phone' (up to 860px) or 'wide' when it only exists at that width
// Pure data, no DOM: a Node script can import it too.

const enc = encodeURIComponent

/** What the links are filled with, from the state the board sends on /events (null before it has arrived). */
export function liveOf(state) {
  if (!state) return {}
  const agents = (state.agents ?? []).filter(a => !a.archived)
  const open = (state.cards ?? []).filter(c => c.status === 'open')
  const first = agents.find(a => a.online && open.some(c => c.agent === a.id)) ?? agents.find(a => a.online) ?? agents[0]
  const grouped = agents.filter(a => a.group && agents.some(b => b !== a && b.group === a.group))
  const pair = grouped.length ? grouped.filter(a => a.group === grouped[0].group).map(a => a.id) : agents.slice(0, 2).map(a => a.id)
  const card = open.find(c => c.agent === first?.id) ?? open[0]
  const pictured = open.find(c => (c.attachments ?? []).some(a => a.image || a.kind === 'image'))
  const past = (state.cards ?? []).find(c => c.status === 'decided' || c.status === 'done')
  const versioned = (state.cards ?? []).find(c => c.versions?.length || c.version > 1)
  let asset = null
  for (const m of state.messages ?? []) { const hit = /\/a\/[\w-]{16,64}#[\w-]{43}/.exec(m.text ?? ''); if (hit) { asset = hit[0]; break } }
  const file = (state.messages ?? []).flatMap(m => m.attachments ?? []).find(a => a.url?.startsWith('/files/'))?.url ?? null
  return {
    session: first?.id ?? null, sessionName: first?.label || first?.name || null,
    pair: pair.length > 1 ? pair : null, paired: grouped.length > 0,
    cardNumber: card?.number ?? null, cardSession: card?.agent ?? null,
    pictured: pictured?.number ?? null, past: past?.number ?? null, versioned: versioned?.number ?? null,
    asset, shared: (state.assets ?? []).find(a => a.share)?.id ?? null, file,
    picture: (() => { for (const a of agents) if ((state.messages ?? []).some(m => m.agent === a.id && (m.attachments ?? []).some(x => x.image || x.kind === 'image')) || (state.cards ?? []).some(c => c.agent === a.id && (c.attachments ?? []).some(x => x.image || x.kind === 'image'))) return `/s/${enc(a.id)}/files/1`; return null })(),
  }
}
const s = (l, tail = '') => (l.session ? `/s/${enc(l.session)}${tail}` : null)
const q = l => (l.cardNumber != null ? `/q/${l.cardNumber}` : null)
const pair = (l, tail = '') => (l.pair ? `/s/${l.pair.map(enc).join('+')}${tail}` : null)

/** The areas, in the order of the page, each with a line of what belongs to it. */
export const AREAS = [
  ['Desk', 'The start page: everything that waits for you, from every session.'],
  ['Card', 'One question. On a wide screen a Desk row unfolds in place; everywhere else the card is a page of its own.'],
  ['Session', 'One session: its conversation, the two filters over it, its canvas. Sessions laid together share a page.'],
  ['Sidebar and bar', 'The list of sessions at the left (a strip on a phone) and the bar with the Desk and the menu.'],
  ['Agents', 'The page of all sessions.'],
  ['Pad and paper', 'The scratchpad, and the canvas of a session (Scribble).'],
  ['Memo', 'The quick note that can be written from anywhere.'],
  ['Menus and sheets', 'Small things that lie over the page: what remains of pop-ups, and how each closes.'],
  ['Notes and errors', 'Passing notices and the ways something going wrong shows.'],
  ['Sign-in and passkeys', 'What somebody without a login sees, and the passkey page.'],
  ['Assets and sharing', 'Published pages and files: the viewer, and the page for somebody outside.'],
  ['Admin and help', 'The two side doors of the menu.'],
  ['Dev and workbenches', 'Pages and switches made for building and testing. None is linked from the app.'],
  ['Design pages', 'Proposal pages under /designs/: drafts that were shown on cards. Static, none is part of the app.'],
  ['Dead code', 'Views that can no longer be reached: the code or the styles are still in the tree.'],
]

export const SCREENS = [
  // ---- Desk ----
  { area: 'Desk', name: 'Desk', status: 'current', to: '/', desc: 'The open questions of all sessions as rows, grouped by who asks; below them the piles Later, Memos and Done.', where: 'js/inbox.js mountInbox, app.js:413' },
  { area: 'Desk', name: 'Desk, empty', status: 'current', to: '/#empty', desc: '"Desk is clear." with its drawing. The link shows it without the hub (hash flag #empty: no state is loaded at all).', where: 'js/inbox.js:1010' },
  { area: 'Desk', name: 'Desk before anything has arrived', status: 'hidden', to: '/#skeleton', desc: 'Hash flag #skeleton never connects. The Desk has no loading state of its own: it says "Desk is clear." until the state is there.', where: 'js/app.js:646' },
  { area: 'Desk', name: '/inbox', status: 'hidden', to: '/inbox', desc: 'An old address the hub still serves as the page. The router does not know it: it shows the Desk and rewrites the address to /.', where: 'server/server.mjs:3103 APP_PATH' },
  { area: 'Desk', name: 'Row unfolded to choose', status: 'current', desc: 'A question with more than two answers: "Choose" unfolds the option tiles, Send, Whatever and the ask-back line in the row.', steps: 'On the Desk, press "Choose" on a row with several options. Escape folds it.', where: 'js/inbox.js:182-291, 670-709' },
  { area: 'Desk', name: 'Pile fanned out (Later, Memos, Done)', status: 'current', desc: 'A click on a pile under the list fans its lines out in place; one pile at a time, "N more" for the rest.', steps: 'On the Desk, click the pile "Later", "Memos" or "Done" below the questions. Escape gathers it.', where: 'js/piles.js:41-140' },
  { area: 'Desk', name: 'Shred instead of Snooze (Shift held)', status: 'current', at: 'wide', desc: 'While Shift is held the quiet tab at a row\'s edge reads "Shred".', steps: 'Hold Shift over the Desk; or key X on the marked row.', where: 'js/bar.js:162, css/app.css body[data-shift]' },
  { area: 'Desk', name: '"N new" and the knock strips', status: 'current', desc: 'A button "N new ↑" when questions arrive above what is in view, and strips at the edges "↑ N knocks" for urgent ones out of sight.', steps: 'Scroll the Desk down while new or urgent questions arrive.', where: 'js/inbox.js:844-909' },
  { area: 'Desk', name: 'Several desks', status: 'current', desc: 'With more than one desk the Desk box names the desk in view and the menu lists the desks (D then 1, 2, …), "New desk…", Rename, Remove.', steps: 'Menu, "+ New desk…".', where: 'js/bar.js:260-369' },
  { area: 'Desk', name: 'Desk paper: pen in hand', status: 'current', to: '/pad', desc: 'The pad lies under the Desk as its paper. /pad (key P) goes to the Desk with the pen in hand: the cards fade and take no pointer until Escape. A pen switch and an eye stand at the lower left.', where: 'js/padlink.js:373 mountDesk; css/deskpad.css' },
  { area: 'Desk', name: 'Desk paper: cards hidden', status: 'current', desc: 'The eye at the lower left hides the Desk\'s cards, so only the paper is left; it then carries the count of knocks. Remembered per browser.', steps: 'On the Desk, press the eye at the lower left.', where: 'js/padlink.js:317 toggleCards' },
  { area: 'Desk', name: 'Desk without the paper', status: 'hidden', to: '/?deskpad=0', desc: 'Query switch ?deskpad=0: the Desk as it was before the paper, with the pad\'s button back in the bar.', where: 'js/padlink.js:25' },

  // ---- Card ----
  { area: 'Card', name: 'Card page', status: 'current', popup: 'page', to: q, desc: 'One question as a page: /q/<number>. Back link at the top left, Escape leaves. The rest of the page is inert under it.', where: 'js/focus.js:3140 open, app.js:323' },
  { area: 'Card', name: 'Card page inside a session', status: 'current', popup: 'page', to: l => (l.cardNumber != null && l.cardSession ? `/s/${enc(l.cardSession)}/q/${l.cardNumber}` : null), desc: 'The same page reached from a session: /s/<id>/q/<number>. The back link names the session.', where: 'js/app.js:55-111' },
  { area: 'Card', name: 'Card unfolded in its Desk row', status: 'current', at: 'wide', desc: 'On a wide screen a click on a row\'s text unfolds the whole card in place; the address reads /q/<number>. A reload of that address gives the card page instead.', steps: 'On the Desk (wider than 860px), click the title of a row.', where: 'js/focus.js:3278 openInline, app.js:345' },
  { area: 'Card', name: 'The walk ("Next, please")', status: 'current', popup: 'page', to: '/walk', desc: 'All open questions one after the other as card pages, the most urgent first, with arrows and "3 of 9".', where: 'js/inbox.js:994, app.js:708 (G F)' },
  { area: 'Card', name: 'The walk of one session', status: 'current', popup: 'page', to: l => s(l, '/walk'), desc: 'The same, through the questions of one session: the badge of a sidebar row starts it.', where: 'js/app.js:390 walkSession' },
  { area: 'Card', name: 'Old card links (?q=)', status: 'hidden', to: l => (l.cardNumber != null ? `/?q=${l.cardNumber}` : null), desc: 'Links from before /q/<n>: ?q=<number>, ?q=<card id>, ?q=next. Still followed and rewritten in place. Over /agents the question still stays in the query.', where: 'js/app.js:77, 106' },
  { area: 'Card', name: '"All answered" at the end of the walk', status: 'current', popup: 'page', desc: 'The walk\'s last page: nothing left, who is still working, Close.', steps: 'Answer the last open question in the walk.', where: 'js/focus.js:352-360' },
  { area: 'Card', name: 'Card with pictures', status: 'current', popup: 'page', to: l => (l.pictured != null ? `/q/${l.pictured}` : null), needs: 'no open question with a picture right now', desc: 'One large picture with a thumb strip; from four pictures that pair with options, "All in a grid".', where: 'js/focus.js:497-611' },
  { area: 'Card', name: 'Picture zoom', status: 'current', popup: 'modal', desc: 'The picture over the whole card with the answers beside it: real size on a click, "All in a grid", "Live" (the page in a frame). Lies over the sheet and traps Tab; Escape, X or a click beside the picture closes.', steps: 'On a card with a picture, press the magnifier on the picture.', where: 'js/focus.js:2919 openZoom' },
  { area: 'Card', name: 'Answered card ("past")', status: 'current', popup: 'page', to: l => (l.past != null ? `/q/${l.past}` : null), needs: 'no answered question on this board right now', desc: 'A decided, shredded or withdrawn card, read-only, with "Take back".', where: 'js/focus.js:1062-1085' },
  { area: 'Card', name: 'Earlier version of a card', status: 'current', popup: 'page', to: l => (l.versioned != null ? `/q/${l.versioned}` : null), needs: 'no revised question on this board right now', desc: 'A revised card keeps its versions: "third version" in the byline steps back through them, read-only.', steps: 'On a revised card, press the version in the byline; J/K step, Escape leaves.', where: 'js/focus.js:1558 viewVersion' },
  { area: 'Card', name: 'Writing on the card (pen)', status: 'current', desc: 'Pen mode: scribble and write anywhere on the card; a pencil in the margin on hover.', steps: 'On a card page, key D, or the pen in the tools row.', where: 'js/focus-marks.js' },
  { area: 'Card', name: 'Card with note rows per option', status: 'hidden', to: l => (l.cardNumber != null ? `/q/${l.cardNumber}?marks=0` : null), desc: 'Query switch ?marks=0: the older way, a note line per option instead of writing on the card.', where: 'js/focus.js:2261' },
  { area: 'Card', name: 'Card with the answers beside the title', status: 'hidden', to: l => (l.cardNumber != null ? `/q/${l.cardNumber}?head=1` : null), desc: 'Query switch ?head=1: an unchosen layout, the answers floated beside the title.', where: 'js/focus.js:2263' },
  { area: 'Card', name: 'Scratchpad in the card\'s composer', status: 'hidden', desc: 'A small drawing pad inside the ask-back line. Its pen button is display:none, so it only opens through an attached picture chip.', steps: 'On a card, attach a picture to the ask-back line, then click its chip.', where: 'js/focus.js:1473-1554, css/focus.css:1101' },
  { area: 'Card', name: 'Card still loading', status: 'current', popup: 'page', desc: 'A card link followed before the board\'s state has arrived: the empty sheet.', steps: 'Reload a /q/<n> address on a slow line.', where: 'js/focus.js:369' },

  // ---- Session ----
  { area: 'Session', name: 'Conversation', status: 'current', to: s, desc: 'A session\'s page: /s/<id>. Messages, its open questions as answerable rows, the composer.', where: 'js/chat.js mountChat' },
  { area: 'Session', name: 'Questions only', status: 'current', to: l => s(l, '/questions'), desc: 'The filter that lays the session\'s questions over the conversation (key Q).', where: 'js/chat.js:455, app.js:233' },
  { area: 'Session', name: 'Files', status: 'current', to: l => s(l, '/files'), desc: 'The filter that lists everything the session sent: pictures, files, published pages (key F).', where: 'js/history.js:48' },
  { area: 'Session', name: 'Scribble (the session\'s canvas)', status: 'current', to: l => s(l, '/scribble'), desc: 'The canvas of the session. From 1200px it stands beside the conversation, below that it takes the pane, with a bar back.', where: 'js/scribble.js, app.js:266' },
  { area: 'Session', name: 'Sessions laid together', status: 'current', to: pair, desc: 'Two or more sessions on one page: /s/<id>+<id>. Their questions as one list, the conversations side by side (a phone: one at a time).', where: 'js/beside.js, chat.js:1091' },
  { area: 'Session', name: 'Laid together: questions instead of the conversation', status: 'current', at: 'phone', desc: 'On a phone a bar "N questions wait for you · Show" swaps the conversation for the joint list.', steps: 'Open sessions laid together at phone width and press the bar.', where: 'js/beside.js:53-66' },
  { area: 'Session', name: 'Laid together: conversations folded to a strip', status: 'current', at: 'wide', desc: 'From 1200px the conversations are a column that can be dragged narrower and folded to a strip.', steps: 'Open sessions laid together on a wide screen, press the fold at the column\'s edge.', where: 'js/beside.js:116-179' },
  { area: 'Session', name: 'Empty conversation', status: 'current', to: '/s/main#empty', desc: 'A session nobody has written to: three suggestions that fill the composer. The link shows it without the hub.', where: 'js/chat.js:398-416' },
  { area: 'Session', name: 'Conversation skeleton', status: 'current', to: l => s(l, '#skeleton'), desc: 'The grey placeholder lines before the first state arrives. The link freezes it (hash flag).', where: 'index.html:149' },
  { area: 'Session', name: 'Conversation scrolled up, with unread', status: 'hidden', to: l => s(l, '#scrolled'), desc: 'Hash flag #scrolled: the log at its top with the button "N new messages".', where: 'js/chat.js:956, 1072' },
  { area: 'Session', name: 'Send error above the composer', status: 'hidden', to: l => s(l, '#error'), desc: 'Hash flag #error shows the inline line a failed send leaves ("Not sent: …").', where: 'js/chat.js:847, 1072' },
  { area: 'Session', name: 'Answered question unfolded in the log', status: 'current', desc: 'A finished question is one quiet line in the conversation; a click unfolds it in place with "Take back".', steps: 'In a conversation, click a line "decided: …".', where: 'js/chat.js:346-388' },
  { area: 'Session', name: 'Old mode flags (#scribble, #decisions, #files)', status: 'hidden', to: '/#decisions', desc: 'Deep links from before there were addresses. Still read on arrival, but without a session in the path they change nothing one can see.', where: 'index.html:62, app.js:495' },

  // ---- Sidebar and bar ----
  { area: 'Sidebar and bar', name: 'Sidebar', status: 'current', desc: 'The sessions, connected first, then "Disconnected". A badge says what waits; a click on it starts that session\'s walk. On a phone it is a strip that scrolls sideways.', steps: 'Always there, except on a card page.', where: 'js/agents.js mountAgents' },
  { area: 'Sidebar and bar', name: 'Sidebar folded to a rail', status: 'current', at: 'wide', desc: 'Drawings and counts only; the name shows beside a row under the pointer. Remembered per browser.', steps: 'Key [ or the small button at the sidebar\'s foot.', where: 'js/bar.js:167-219' },
  { area: 'Sidebar and bar', name: 'Main agent with its helpers folded', status: 'current', desc: 'A crowned session with helpers: the crown folds them under it (stacked edges) or opens them (a bracket).', steps: 'Click the crown of a session that has helpers.', where: 'js/agents.js:414-450' },
  { area: 'Sidebar and bar', name: 'Dragging a session', status: 'current', desc: 'Onto the middle of another row lays the two together, onto an edge moves it, out of a group takes it out. Touch: hold first.', steps: 'Drag a sidebar row.', where: 'js/agents.js:498-637' },
  { area: 'Sidebar and bar', name: 'Key hint "g …" and numbered rows', status: 'current', desc: 'After G the bar shows what may follow and the first ten sidebar rows carry their number.', steps: 'Press G on the Desk.', where: 'js/keys.js:196-220, css/keys.css' },
  { area: 'Sidebar and bar', name: 'Tight phone bar', status: 'current', at: 'phone', desc: 'When the counts no longer fit, the Agents button leaves the bar (it stays in the menu).', steps: 'At phone width with long counts in the Desk box.', where: 'js/bar.js:381-399' },

  // ---- Agents ----
  { area: 'Agents', name: 'Agents', status: 'current', to: '/agents', desc: 'Every session as a line of a ledger: state, what it asks or does, model, machine, last seen. Sortable, searchable (/), with Disconnected and the Archive below.', where: 'js/ledger.js:554' },
  { area: 'Agents', name: 'A question opened over Agents', status: 'current', popup: 'page', to: l => (l.cardNumber != null ? `/agents?q=${l.cardNumber}` : null), desc: 'From a ledger line the card opens as ?q=<n>: the hub serves no /agents/q/<n>.', where: 'js/ledger.js:52-57' },
  { area: 'Agents', name: 'Laying together, in the ledger', status: 'current', desc: 'A line is picked ("Laying X together with: pick the other line…"), a click on a second one joins them.', steps: 'On Agents, press the heads icon of a line (or +), then another line. Escape lets go.', where: 'js/ledger.js:383-389' },
  { area: 'Agents', name: 'Archive', status: 'current', desc: 'Archived sessions, at the foot of the Agents page, each with "Fetch back". The only place they come back from.', steps: 'Archive a disconnected session (sidebar or Agents), then scroll Agents to its end.', where: 'js/ledger.js:345-362' },
  { area: 'Agents', name: 'Agents, nothing found', status: 'current', desc: '"No session fits. Show all" under the search field.', steps: 'On Agents press / and type something no session is called.', where: 'js/ledger.js:336-341' },

  // ---- Pad and paper ----
  { area: 'Pad and paper', name: 'Scratchpad over the board (the old overlay)', status: 'hidden', popup: 'page', to: '/pad?deskpad=0', desc: 'Before the Desk had its paper, the pad filled the screen over the page at /pad. Still alive behind ?deskpad=0; Escape or Back closes it.', where: 'js/padlink.js:154 show' },
  { area: 'Pad and paper', name: 'Scratchpad as its own page', status: 'hidden', to: '/pad/', desc: 'The pad without the board around it (mind the slash). Not linked from the app; the overlay loads it in a frame as /pad/?embed=1.', where: 'pad/index.html, pad/pad.js' },
  { area: 'Pad and paper', name: 'A second pad by name', status: 'hidden', to: '/pad/?pad=test', desc: 'Query switch ?pad=<name>: another pad than the one everybody shares ("global").', where: 'pad/pad.js:21-28' },
  { area: 'Pad and paper', name: 'Pad: send a selection', status: 'current', popup: 'anchored', desc: 'A panel at the selection with a preview of what goes to the session, and Send; what was sent then leaves the paper. No veil; Escape, Close or a click beside it closes.', steps: 'On the pad, select something, "Send to…", pick a session.', where: 'pad/index.html:105, pad/pad.js openSendDialog' },
  { area: 'Pad and paper', name: 'Pad: keys', status: 'current', popup: 'modal', desc: 'The pad\'s own list of shortcuts: a sheet in the middle without a veil, like the board\'s; Escape, the X or a click beside it closes.', steps: 'On the pad press ? or the help button.', where: 'pad/index.html:130' },
  { area: 'Pad and paper', name: 'Pad: recording', status: 'current', desc: 'A pill "Recording" with Done and discard while speech is taken down onto the pad.', steps: 'On the pad hold the pointer down for half a second, or press M (needs the speech service).', where: 'pad/pad.js:770' },
  { area: 'Pad and paper', name: 'Scribble: colour and width', status: 'current', popup: 'anchored', desc: 'A small panel above the toolbar. Closes by its button, Escape, or a touch on the canvas.', steps: 'On a session\'s Scribble, press the active pen again.', where: 'js/scribble.js:433-444' },
  { area: 'Pad and paper', name: 'Scribble: "Clear everything?"', status: 'current', popup: 'anchored', desc: 'The one confirmation of the canvas, a small panel under the bin (no veil). Clearing can be undone.', steps: 'On a session\'s Scribble, press the bin.', where: 'js/scribble.js:402-413' },
  { area: 'Pad and paper', name: 'Scribble: send a region', status: 'current', desc: 'A frame drawn with the region tool gets its own small bar: send this part, or discard.', steps: 'On Scribble press R and drag a frame; Enter sends, Escape drops it.', where: 'js/scribble.js:474-482' },
  { area: 'Pad and paper', name: 'Scribble could not be loaded', status: 'current', desc: 'The fallback line in the pane when the canvas module fails to load.', steps: 'Only when js/scribble.js fails to load.', where: 'js/app.js:284-287' },

  // ---- Memo ----
  { area: 'Memo', name: 'Memo, floating', status: 'current', at: 'wide', popup: 'anchored', desc: 'A note that floats over the page, can be dragged, survives navigation and a reload. Several at once. No veil; Escape puts it on the stack.', steps: 'Key / or the round button at the bottom right.', where: 'js/quicksend.js:114 makeView' },
  { area: 'Memo', name: 'Memo as a sheet', status: 'current', at: 'phone', popup: 'modal', desc: 'On a phone the memo is a sheet at the lower edge with a veil over the page (css/quicksend.css:139). A tap on the veil or Escape puts it away.', steps: 'At phone width, the round button at the bottom right.', where: 'js/quicksend.js:394-425' },
  { area: 'Memo', name: 'Memos pile on the Desk', status: 'current', desc: 'Notes put away lie as lines in the pile "Memos" under the Desk\'s questions; a click floats one again.', steps: 'Write a memo, press Escape, then open "Memos" on the Desk.', where: 'js/memos.js:105, inbox.js:1077' },
  { area: 'Memo', name: 'Memo on the paper', status: 'current', at: 'wide', desc: 'A floating memo dropped onto the Desk\'s paper lies there as part of it.', steps: 'On the Desk, drag a memo by its head onto the paper.', where: 'js/quicksend.js:335, 366-377' },

  // ---- Menus and sheets ----
  { area: 'Menus and sheets', name: 'Trommi menu', status: 'current', popup: 'anchored', desc: 'Jump field, desks, Agents, Help, Admin, Keys, the connection, knock sound, theme, Dev. No veil; Escape, a choice or a click beside it closes.', steps: 'Click "Trommi" at the top (a phone: the caret in the bar), or Ctrl/Cmd+K.', where: 'js/bar.js:76-115' },
  { area: 'Menus and sheets', name: 'Jump results', status: 'current', popup: 'anchored', desc: 'Typing in the menu\'s field lists sessions, "Question Nr. n", Desk, Agents, Scratchpad; Enter takes the first.', steps: 'Ctrl/Cmd+K, type.', where: 'js/bar.js:117-159' },
  { area: 'Menus and sheets', name: 'Keys sheet', status: 'current', popup: 'modal', desc: 'Every key that works in the view that is up. A dialog in the middle of the page, since today without a veil; ?, Escape or a click beside it closes. Not offered on touch devices.', steps: 'Press ? or Menu, Keys.', where: 'js/keys.js:324-375' },
  { area: 'Menus and sheets', name: 'Choose a drawing', status: 'current', popup: 'anchored', desc: 'Forty drawings in a grid right under the session\'s mark; one click picks and saves. No veil.', steps: 'In a session, click its drawing left of the name; on Agents, the drawing of a line (key D).', where: 'js/agents.js:654 openMarkPicker' },
  { area: 'Menus and sheets', name: 'Rename a session', status: 'current', popup: 'anchored', desc: 'A small form right at the name that was pressed. Since today no longer a modal in the middle with a veil; Enter saves, Escape or a click beside it closes.', steps: 'In a session, click its name; on Agents, the name of a line (key R).', where: 'js/agents.js:708 openEditor' },
  { area: 'Menus and sheets', name: 'Row menu after a long press', status: 'current', at: 'phone', popup: 'anchored', desc: 'A sheet at the lower edge with a row\'s ways out: Snooze, Revise, Whatever, What??, Shred, Copy. Since today without a veil; a tap beside it or Escape closes.', steps: 'At phone width, hold a finger on a Desk row (or right click).', where: 'js/inbox.js:313 holdMenu' },
  { area: 'Menus and sheets', name: 'Agents: sheet of one line', status: 'current', at: 'phone', popup: 'anchored', desc: 'What a wide line offers beside it: open, rename, drawing, crown, lay together, archive, move to a desk. Since today without a veil.', steps: 'At phone width on Agents, press "…" on a line.', where: 'js/ledger.js:279-302' },
  { area: 'Session', name: 'Picture, large', status: 'current', popup: 'page', to: l => (l.picture ?? null), needs: 'no picture in a session right now', desc: 'A picture as a page of its own: /s/<id>/files/<n>, n counting the session\'s pictures from the oldest. No veil. Back, Escape or the link at the top left closes it; the arrows are links to the picture before and after.', where: 'js/chat.js lightbox, followPicture' },
  { area: 'Menus and sheets', name: 'Agent layout, large', status: 'current', to: '/large.html', desc: 'A block of HTML an agent sent, as a page in a new tab (/large.html#<key>), in the same sandboxed frame. No longer a window over the board. The bare link shows its "no longer here" line.', steps: 'In a message or card with a layout block, press "Open large".', where: 'large.html, js/richhtml.js largeBlock' },
  { area: 'Menus and sheets', name: 'Share an asset', status: 'current', desc: 'Not a pop-up: the panel unfolds in the asset\'s card. "Create outside link", the link, when it ends, "Stop sharing".', steps: 'In a conversation, press "Share" on a published page or file.', where: 'js/ui.js:103-192' },
  { area: 'Menus and sheets', name: 'Desk: rename, remove, new', status: 'current', desc: 'In the menu, in place: a field instead of the desk\'s line; "Remove" asks "Really remove?" on the same button for four seconds.', steps: 'Menu, on the desk in view: Rename or Remove.', where: 'js/bar.js:271-357' },

  // ---- Notes and errors ----
  { area: 'Notes and errors', name: '"Answered" note with Back', status: 'current', popup: 'note', to: '/#undo', desc: 'After an answer: what was answered, and Back for five seconds (the key for ten). Beside the answer on a wide screen, a strip under the list on a phone. Blocks nothing. The link shows a sample.', where: 'js/back.js:126 say, app.js:592' },
  { area: 'Notes and errors', name: 'Error notice (toast)', status: 'current', popup: 'note', to: '/#toast', desc: 'The page\'s one passing error line, four to six seconds: canvas did not load, "Not taken back". The link shows a sample that stays.', where: 'js/app.js:571-589' },
  { area: 'Notes and errors', name: 'Disconnected', status: 'current', to: '/#offline', desc: 'The hub does not answer: the pill in the menu\'s foot reads "Disconnected, reconnecting" and the menu\'s caret carries a dot. No pop-up; the browser reconnects by itself. The link shows a sample.', where: 'js/app.js:549-565' },
  { area: 'Notes and errors', name: 'Memo and copy notes', status: 'current', popup: 'note', desc: '"Sent to X. Open the conversation", "Note thrown away. Take it back", "Copied — paste it into a session": quiet lines at the lower edge, a few seconds.', steps: 'Send a memo; copy a card (Ctrl+C on a marked row).', where: 'js/quicksend.js:48-71, cardclip.js:62-74' },
  { area: 'Notes and errors', name: 'Error on a card', status: 'current', desc: '"Not saved: …" stands on the card itself, with a shake; the feed says "Not sent: …".', steps: 'Answer a card while the hub is down.', where: 'js/focus.js:815, 1104' },
  { area: 'Notes and errors', name: 'Error on a row, in the menu, in the ledger', status: 'current', desc: 'Each where the action was: under the row, under the Desk\'s head (5 s), in the menu ("Needs the hub restart.", "Not saved: …"), in the ledger\'s note line.', steps: 'Any action while the hub is down or older than the page.', where: 'js/inbox.js:382, 796; bar.js:231, 268; ledger.js:126' },
  { area: 'Notes and errors', name: 'Passkey prompt', status: 'current', popup: 'modal', desc: 'The browser\'s own: the passkey sheet on sign-in. No microphone prompt (dictation was removed, out of scope for launch), no notification prompt, no "leave this page?" prompt anywhere.' },
  { area: 'Notes and errors', name: 'Not found', status: 'current', to: '/no-such-page', desc: 'An address the hub does not know: the bare line {"error":"not found"}. There is no 404 page.', where: 'server/server.mjs:3554' },

  // ---- Sign-in and passkeys ----
  { area: 'Sign-in and passkeys', name: 'Sign-in page', status: 'current', desc: 'What a page request without a login gets (status 401): "Sign in with a passkey" and a note about the link. Without passkeys: one plain line.', steps: 'Open the board in a private window, without the ?t= link.', where: 'server/passkey.mjs signInPage, server.mjs:3155' },
  { area: 'Sign-in and passkeys', name: 'Passkeys', status: 'hidden', to: '/passkeys', desc: 'The list of passkeys with Remove, and "Add a passkey on this device". Linked from nowhere in the app. Its Remove is the one browser confirm() left (server/passkey.mjs:416).', where: 'server/passkey.mjs' },
  { area: 'Sign-in and passkeys', name: 'Login link', status: 'current', desc: 'Any address with ?t=<token> signs in and redirects to itself without the token.', steps: 'The link in data/url.txt.', where: 'server/server.mjs:3128' },

  // ---- Assets and sharing ----
  { area: 'Assets and sharing', name: 'Asset viewer', status: 'current', to: l => l.asset, needs: 'no published page in a conversation right now', desc: '/a/<id>#<key>: a published page in a sandboxed frame, a picture, video, sound, or a file to download. Decrypted in the browser.', where: 'a.html, js/asset.js' },
  { area: 'Assets and sharing', name: 'Asset viewer: no key', status: 'current', to: '/a/AAAAAAAAAAAAAAAAAAAAAA', desc: 'The viewer\'s problem states: no key in the address (this link), a wrong key, gone, too many requests, offline, unknown format.', where: 'js/asset.js:66-89, 156' },
  { area: 'Assets and sharing', name: 'Asset viewer: gone', status: 'current', to: '/a/AAAAAAAAAAAAAAAAAAAAAA#AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', desc: 'What a link shows whose asset was withdrawn, has run out, or never existed.', where: 'js/asset.js:68' },
  { area: 'Assets and sharing', name: '"Shared with you"', status: 'current', to: '/r/AAAAAAAAAAAAAAAAAAAAAA#AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA', desc: '/r/<id>#<key>: the page somebody outside gets for an asset that was released. Follows the system\'s theme, needs no login. The link shows its "gone" state.', where: 'server/share-viewer.mjs' },
  { area: 'Assets and sharing', name: 'An uploaded file', status: 'current', to: l => l.file, needs: 'no attachment in a conversation right now', desc: '/files/<name>: an attachment as the browser shows it. This is what "Open the original" leads to.', where: 'server/server.mjs:3187' },

  // ---- Admin and help ----
  { area: 'Admin and help', name: 'Admin', status: 'current', to: '/admin.html', desc: 'Behind a key of its own (data/admin-token): overview, sessions (discard, forget), cleanup, access links, export, diagnosis. Its confirmations are inline.', where: 'admin.html, js/admin.js' },
  { area: 'Admin and help', name: 'Help', status: 'current', to: '/help.html', desc: 'How the board works, the keys, and for agents: events and tools, read from the hub.', where: 'help.html, js/help.js' },
  { area: 'Admin and help', name: 'Help: the keys', status: 'current', to: '/help.html#keys', desc: 'The whole table of keys as a section of a page (the "?" sheet lists only those of the view that is up).', where: 'js/help.js:183' },
  { area: 'Admin and help', name: 'Help: the diagram alone', status: 'hidden', to: '/help.html#diagram', desc: 'Hash flag #diagram: only the picture of how agents and the board talk, on white. Made for screenshots.', where: 'help.html:15' },

  // ---- Dev and workbenches ----
  { area: 'Dev and workbenches', name: 'All screens', status: 'current', to: '/screens.html', desc: 'This page. Menu, Dev, "All screens".', where: 'screens.html, js/screens.js' },
  { area: 'Dev and workbenches', name: 'Fake decisions', status: 'current', desc: 'Menu, Dev: "Create 5 fake decisions" throws test cards onto the Desk, "Remove fake decisions" takes them away.', steps: 'Menu, Dev.', where: 'js/bar.js:221-258' },
  { area: 'Dev and workbenches', name: 'Dark or light by link', status: 'hidden', to: '/#dark', desc: 'Hash flags #dark and #light set the theme for this load, whatever is remembered. Also on Admin, Help and the pad.', where: 'index.html:12-17' },
  { area: 'Dev and workbenches', name: 'Focus workbench', status: 'hidden', to: '/focus-preview.html', desc: 'The card page with sample questions and no hub, with hash flags for its states.', where: 'focus-preview.html' },
  { area: 'Dev and workbenches', name: 'Scribble workbench', status: 'hidden', to: '/scribble-preview.html', desc: 'The canvas alone, with hash flags for its states (style panel open, confirmation open, …).', where: 'scribble-preview.html' },
  { area: 'Dev and workbenches', name: 'Board without a server (hash routes)', status: 'hidden', to: '/#/agents', desc: 'Opened as a file, or with "#/" in the address, every route stands behind the hash: #/s/<id>/q/<n>. A page opened that way keeps writing them that way.', where: 'js/app.js:67, link.js:17' },
  { area: 'Dev and workbenches', name: 'Old notes: layouts', status: 'hidden', to: '/layouts.html', desc: 'A German design note: five ways to separate decisions from the conversation.', where: 'layouts.html' },
  { area: 'Dev and workbenches', name: 'Old notes: naming', status: 'hidden', to: '/naming.html', desc: 'The study of names and domains.', where: 'naming.html' },
  { area: 'Dev and workbenches', name: 'Old notes: crypto concept', status: 'hidden', to: '/krypto-konzept.html', desc: 'The concept for keys and encryption (German).', where: 'krypto-konzept.html' },
  { area: 'Dev and workbenches', name: 'Old notes: tech stack', status: 'hidden', to: '/tech-stack.html', desc: 'A memo on the stack. Nothing links to it.', where: 'tech-stack.html' },
  { area: 'Dev and workbenches', name: 'Old notes: Scribble in the conversation', status: 'hidden', to: '/scribble-vorschlag.html', desc: 'A proposal page (German). Nothing links to it.', where: 'scribble-vorschlag.html' },
  { area: 'Dev and workbenches', name: 'Health check', status: 'hidden', to: '/healthz', desc: '{"ok":true}, for a supervisor. Needs no login.', where: 'server/server.mjs:3126' },
  { area: 'Dev and workbenches', name: 'Tools as data', status: 'hidden', to: '/api/tools', desc: 'The JSON the help page draws its reference from.', where: 'server/server.mjs:3164' },

  // ---- Dead code ----
  { area: 'Dead code', name: 'Phone tab bar (Conversation / Scribble)', status: 'dead', desc: 'nav.tabbar at the foot of index.html is display:none at every width and in every place. Its two links still carry click listeners, and the toast still measures it.', where: 'index.html:169-183, css/app.css:499, 1206, 1575' },
  { area: 'Dead code', name: 'Mode switch in the session head', status: 'dead', desc: '"Conversation / Scribble" in the pane title is never displayed. It only lives on as the thing other code clicks. With it the unread dot (#chat-dot) can never be seen.', where: 'index.html:138-141, css/app.css:1206, app.js:204' },
  { area: 'Dead code', name: 'Footnav (Desk, Agents buttons)', status: 'dead', desc: 'The two buttons in the bar are display:none for good; every place in the code that wants to go to the Desk or Agents clicks them unseen.', where: 'index.html:114-117, css/app.css:1314' },
  { area: 'Dead code', name: 'Focus button in the bar', status: 'dead', desc: '#focus-open carries the hidden attribute and nothing takes it off. It stays as the spot the pad\'s button is put before.', where: 'index.html:121, app.js:379' },
  { area: 'Dead code', name: 'The walk as a scrolling list', status: 'dead', desc: 'LIST_WALK = false: the walk that laid all cards on one long page. Its code, its end piles, its strips and about 150 lines of styles are still there.', where: 'js/focus.js:116, 2270-2505; css/focus.css:673-736' },
  { area: 'Dead code', name: 'The card\'s old top bar', status: 'dead', desc: 'Sender, tab, time, Close and the hint "More urgent: …" in .focus-top: display:none on the card page, so its hints are only heard by screen readers.', where: 'js/focus.js:276-313, css/focus.css:1510' },
  { area: 'Dead code', name: 'Card buttons never placed', status: 'dead', desc: 'Later, Explain and Hand back as buttons of the card (laterBtn, explainBtn, handBtn) are built and never put on the page; the "Discuss" block has styles and no element.', where: 'js/focus.js:290, 294, 2197; css/focus.css:970-1023' },
  { area: 'Dead code', name: 'Revise by opening the card', status: 'dead', desc: 'openFocus(…, { revise }) returns before the line that would open Discuss: Revise always hands back at once.', where: 'js/app.js:330-334' },
  { area: 'Dead code', name: 'Toast with a button ("undo" kind)', status: 'dead', desc: 'showToast takes an action nobody passes any more: the Back note replaced it. Its styles remain.', where: 'js/app.js:579, css/app.css:493-496' },
  { area: 'Dead code', name: 'The old quick-send bar', status: 'dead', desc: 'Styles for a .quick bar with a card clip in it; the memo replaced the bar and nothing creates it.', where: 'css/cardclip.css:41-46' },
  { area: 'Dead code', name: 'The old "answered" group and pile parts', status: 'dead', desc: 'Styles for an answered group on the Desk and for pile parts (fold, peek, tally) that nothing creates since the piles were rebuilt.', where: 'css/back.css:66-82, css/app.css:1027-1062' },
  { area: 'Dead code', name: '"All sessions" row of the sidebar', status: 'dead', desc: 'Styles for .agent-all; no code creates it. Of the old roster only the name is left: body[data-page="roster"] is the Agents page.', where: 'css/app.css:544-546' },
]

// The design pages under client/web/designs/, by theme: [file, title]. Titles are the pages' own, put into English
// where the page is German. A third word marks a page that no longer shows what it was made for: "stale" (it decorates
// a part of the live board that has changed since). A snapshot, made by a script on the day this was written;
// a page added later is added here by hand.
export const DESIGNS = [
  ["Whole layouts (drafts A to S, W2)", [
    ["a.html","Draft A: Desk"],
    ["b.html","Draft B: Stack"],
    ["c.html","Draft C: Scroll"],
    ["c1.html","Draft C1: Column"],
    ["c2.html","Draft C2: Sheet"],
    ["c3.html","Draft C3: Piles"],
    ["c4.html","Draft C4: Zoom"],
    ["c5.html","Draft C5: Regions"],
    ["d.html","Draft D: Workbench"],
    ["e.html","Draft E: Letter"],
    ["g1.html","Draft G1: Tabletop"],
    ["g2.html","Draft G2: Cards"],
    ["g3.html","Draft G3: Ledger"],
    ["g4.html","Draft G4: Lanes"],
    ["index.html","Layout drafts"],
    ["interface.html","Trommi interface: what agents can send and get"],
    ["nosidebar-canvas.html","Trommi without a sidebar · Canvas desk"],
    ["nosidebar-classic.html","Trommi without a sidebar · Sidebar, as before"],
    ["nosidebar-crumb.html","Trommi without a sidebar · Crumb"],
    ["nosidebar-desk.html","Trommi without a sidebar · Desk"],
    ["nosidebar-edge.html","Trommi without a sidebar · Edge"],
    ["nosidebar-fan.html","Trommi without a sidebar · Fan"],
    ["nosidebar-ledger.html","Trommi without a sidebar · Ledger"],
    ["nosidebar-pill.html","Trommi without a sidebar · Pill"],
    ["nosidebar-shelf.html","Trommi without a sidebar · Shelf"],
    ["nosidebar-strip.html","Trommi without a sidebar · Strip"],
    ["nosidebar-switcher.html","Trommi without a sidebar · Switcher"],
    ["nosidebar-tabs.html","Trommi without a sidebar · Tabs"],
    ["s1.html","Draft S1: Rail"],
    ["s5.html","Draft S5: Table"],
    ["stand.html","State of things"],
    ["takeovers.html","Takeovers: before and after"],
    ["w2a.html","Draft W2A: Tabs"],
    ["w2b.html","Draft W2B: Pill"],
    ["w2c.html","Draft W2C: Marks"],
  ]],
  ["Desk, piles and rows", [
    ["actions-under-field.html","Actions under the field"],
    ["actions-under-options.html","Actions under the options"],
    ["buttons.html","Ten answer buttons"],
    ["desk-menu.html","Several desks"],
    ["desk-tabs.html","Several desks"],
    ["deskmark.html","The Desk drawing"],
    ["ears.html","Ten ears: the Snooze corner"],
    ["group-pile.html","Runs of one session: Pile"],
    ["group-sheet.html","Runs of one session: Sheet"],
    ["group-spine.html","Runs of one session: Spine"],
    ["group-tab.html","Runs of one session: Tab"],
    ["group-tiny.html","Runs of one session: Tiny"],
    ["iphone-checks.html","Seven checks on the iPhone"],
    ["phone-bar.html","The Desk on a phone"],
    ["phone-calm.html","The Desk on a phone"],
    ["phone-list.html","The Desk on a phone"],
    ["phone-one.html","The Desk on a phone"],
    ["phone-sheet.html","The Desk on a phone"],
    ["piles-bar.html","Piles: In the bar"],
    ["piles-folds.html","Piles: Folds"],
    ["piles-ledger.html","Piles: Ledger"],
    ["piles-line.html","Piles: One line"],
    ["piles-margin.html","Piles: Margin"],
    ["piles-pegs.html","Piles: Pegs"],
    ["piles-tabs.html","Piles: Tabs"],
    ["piles-tally.html","Piles: Tally"],
    ["piles-today.html","Piles: Today line"],
    ["piles-trays.html","Piles: Trays"],
    ["piles5.html","Four equal piles"],
    ["rowacts-above.html","The row's four"],
    ["rowacts-below.html","The row's four"],
    ["rowacts-flag.html","The row's four"],
    ["rowacts-hover.html","The row's four"],
    ["rowacts-two.html","The row's four"],
    ["rowacts-under.html","The row's four"],
    ["rows.html","Ten rows: Later, number, time"],
    ["runs.html","Who asks, in a fixed order"],
    ["simple-bin.html","Fewer buttons"],
    ["simple-four.html","Fewer buttons"],
    ["simple-keys.html","Fewer buttons"],
    ["simple-merge.html","Fewer buttons"],
    ["simple-one.html","Fewer buttons"],
    ["simple-two.html","Fewer buttons"],
    ["thumbs-choose.html","Thumbs without words"],
    ["thumbs-labels.html","Thumbs without words"],
    ["thumbs-now.html","Thumbs without words"],
    ["thumbs10.html","Two long answers on the row"],
    ["trio.html","The three buttons: six sets"],
    ["whatever10.html","Whatever as an alternative to deciding"],
  ]],
  ["Card and answers", [
    ["advice-bracket.html","Advice mark: Bracket"],
    ["advice-circle.html","Advice mark: Circle"],
    ["advice-hand.html","Advice mark: Hand"],
    ["advice-handline.html","Advice mark: Hand + underline"],
    ["advice-marker.html","Advice mark: Marker"],
    ["advice-star.html","Advice mark: Star"],
    ["advice-underline.html","Advice mark: Underline"],
    ["advice.html","Five ways to mark the advice"],
    ["card-back.html","Card and notes"],
    ["card-decided.html","Card and notes"],
    ["card-margin.html","Card and notes"],
    ["card-memo.html","Card and notes"],
    ["card-unfold.html","Card and notes"],
    ["current-arrow.html","Current option: Drawn arrow"],
    ["current-bar.html","Current option: Bar"],
    ["current-caret.html","Current option: Caret"],
    ["current-corners.html","Current option: Corners"],
    ["current-deeper.html","Current option: Deeper fill"],
    ["current-lift.html","Current option: Lifted"],
    ["handback.html","The hand-back word: like Revise, but better"],
    ["nextplease.html","Next, please"],
    ["trust-arrow.html","Trust: Whatever you say"],
    ["trust-fine.html","Trust: Fine by me"],
    ["trust-initials.html","Trust: Initial it"],
    ["trust-shrug.html","Trust: Shrug"],
    ["trust-stamp.html","Trust: OK stamp"],
    ["trust-sure.html","Trust: Sure, go"],
    ["trust-surprise.html","Trust: Surprise me"],
    ["trust-wave.html","Trust: Wave it through"],
    ["trust-whatever.html","Trust: Whatever"],
    ["trust-yourcall.html","Trust: Your call"],
    ["vip.html","VIP marking: five candidates"],
    ["vip2.html","Ten VIP tickets"],
    ["walk-form.html","\"Next, please\": five forms"],
    ["walk-word.html","The word on the walk button"],
  ]],
  ["Sidebar, sessions, crowns", [
    ["bar-agents.html","Tight top bar"],
    ["bar-counts.html","Tight top bar"],
    ["crown-bracket.html","Crowns and subjects"],
    ["crown-caption.html","Crowns and subjects"],
    ["crown-columns.html","Crowns and subjects"],
    ["crown-fold.html","Crowns and subjects"],
    ["crown-ground.html","Crowns and subjects"],
    ["crown-line.html","Crowns and subjects"],
    ["crown-marks.html","Crowns and subjects"],
    ["crown-stack.html","Crowns and subjects"],
    ["crown-stripe.html","Crowns and subjects"],
    ["crown-tree.html","Crowns and subjects"],
    ["crown.html","Crowns and subjects"],
    ["joined-folded.html","Sessions laid together: Questions first"],
    ["joined-merged.html","Sessions laid together: One timeline"],
    ["joined-stacked.html","Sessions laid together: Stacked"],
    ["joined-tabs.html","Sessions laid together: Tabs"],
    ["rail-fold.html","Narrow sidebar"],
    ["rail-none.html","Narrow sidebar"],
    ["row-both.html","Sidebar row: Both"],
    ["row-hand.html","Sidebar row: Hand"],
    ["row-left1.html","Sidebar row: Swap"],
    ["row-left2.html","Sidebar row: Over"],
    ["row-left3.html","Sidebar row: Beside"],
    ["row-left4.html","Sidebar row: Right"],
    ["row-mark.html","Sidebar row: Mark"],
    ["row-orbit.html","Sidebar row: Orbit"],
    ["row-pen.html","Sidebar row: Pen"],
    ["row-runner.html","Sidebar row: Runner"],
    ["row-today.html","Sidebar row: Today"],
    ["row-track.html","Sidebar row: Track"],
    ["row.html","Sidebar row variants"],
    ["sessions-explained.html","Is a subagent a session?"],
  ]],
  ["Menu", [
    ["float5.html","Floating menu"],
    ["menu-cmd.html","Desk and menu · Command"],
    ["menu-corner.html","Desk and menu · Corner"],
    ["menu-float.html","Desk and menu · Floating desk"],
    ["menu-foot.html","Desk and menu · Sidebar foot"],
    ["menu-split.html","Desk and menu · Split"],
    ["menu-top.html","Desk and menu · Desk head"],
  ]],
  ["Memo, quick send, dictation", [
    ["bubble-inside.html","Quick-send bubble: Drawing in the bubble","stale"],
    ["bubble-mark.html","Quick-send bubble: The drawing","stale"],
    ["bubble-tick.html","Quick-send bubble: Drawing with a bubble tick","stale"],
    ["diktat-menue.html","Three unclear dictations"],
    ["diktat-stapel.html","Three unclear dictations","stale"],
    ["diktat-zeichnung.html","Three unclear dictations"],
    ["live-bubble.html","Without a send button"],
    ["live-field.html","Without a send button"],
    ["quick-bar.html","Quick send: bar"],
    ["quick-chat.html","Quick send: chat"],
    ["quick-dictaphone.html","Quick send: dictaphone"],
    ["quick-memo.html","Quick send: memo"],
    ["quick-pad.html","Quick send: pad"],
    ["quick-plane.html","Quick send: plane"],
    ["quick-sticky.html","Quick send: sticky"],
    ["quick-telegram.html","Quick send: telegram"],
    ["quick-tray.html","Quick send: tray"],
    ["quick-tube.html","Quick send: tube"],
  ]],
  ["Logo, name and words", [
    ["brand.html","The name, for America"],
    ["landing.html","one desk for your coding agents"],
    ["logo-bell.html","Logo · counter bell, hand-drawn"],
    ["logo-brush.html","Trommi logo · Brush"],
    ["logo-dash.html","Trommi logo · One stroke"],
    ["logo-double.html","Trommi logo · Twice over"],
    ["logo-flourish.html","Trommi logo · Underline"],
    ["logo-fold.html","Trommi logo · Folded corner"],
    ["logo-ring.html","Trommi logo · Circled"],
    ["logo-strike.html","Trommi logo · Struck through"],
    ["logo-tick.html","Trommi logo · Ends in a tick"],
    ["logo-z.html","Trommi logo · eight scribbled Z"],
    ["logo.html","Logo without a Z"],
    ["logo10.html","Logo without a Z · ten marks"],
    ["names-bang.html","Thirty names with a bang"],
    ["names-com.html","Ten names with a free .com"],
    ["names-domains.html","Ten names: .com only"],
    ["names-inbox.html","A name for the inbox: six candidates"],
    ["names.html","Ten German-sounding names"],
    ["words-directions.html","Inbox word: which direction?"],
    ["words-inbox.html","One word for the inbox: 40 candidates"],
    ["words-napkin-scratch.html","Napkin, Scratch or Scribble"],
    ["words-pad.html","A word for the pad: 20 candidates"],
    ["words-sidebar.html","Inbox word?"],
  ]],
  ["Architecture and concept", [
    ["architecture.html","Trommi architecture: the ideal and today"],
    ["assets.html","Trommi assets"],
    ["crypto-picture.html","Trommi keys, in pictures"],
    ["open-source.html","what to open, what to keep"],
    ["stack.html","Trommi stack: hub and web app"],
  ]],
  ["Other", [
    ["tabicon.html","Tab icon: square or bare"],
  ]],
]
