// Writes core/doodle_data.inc: the points of the named drawings, the sketched
// icons, the raised hand and the crown, taken from client/web/js/ui.js, so the
// C++ port (core/doodle.cpp) draws from the same numbers as the web.
//   node client/linux/tools/doodle-data.mjs
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const src = fs.readFileSync(path.join(here, '..', '..', 'web', 'js', 'ui.js'), 'utf8')
const cut = (from, to) => {
  const a = src.indexOf(from), b = src.indexOf(to, a)
  if (a < 0 || b < 0) throw new Error(`ui.js has no "${from}" … "${to}"`)
  return src.slice(a, b)
}
const { NAMED, SKETCH, HAND, CROWN } = new Function(`
  ${cut('const straight =', 'const KINDS')}
  ${cut('const CROWN =', '/** The mark of a starred session')}
  ${cut('const flip =', '/** An icon drawn like the session marks')}
  ${cut('const HAND = [', '/** The mark of the agent')}
  return { NAMED, SKETCH, HAND, CROWN }`)()

const num = n => (Number.isInteger(n) ? `${n}` : `${n}`)
const stroke = s => `{${s.straight ? 'true' : 'false'}, {${s.map(([x, y]) => `{${num(x)}, ${num(y)}}`).join(', ')}}}`
const table = (name, map) => `static const QList<QPair<QString, QList<Stroke>>> ${name} = {\n${Object.entries(map).map(([k, strokes]) => `    {QStringLiteral("${k}"), {${strokes.map(stroke).join(', ')}}},`).join('\n')}\n};\n`
const out = `// Generated by tools/doodle-data.mjs from client/web/js/ui.js. Do not edit.
${table('NAMED', NAMED)}
${table('SKETCH', SKETCH)}
static const QList<QPointF> HAND = {${HAND.map(([x, y]) => `{${x}, ${y}}`).join(', ')}};
static const char *CROWN = "${CROWN}";
`
const file = path.join(here, '..', 'core', 'doodle_data.inc')
fs.writeFileSync(file, out)
console.log(`${Object.keys(NAMED).length} drawings, ${Object.keys(SKETCH).length} sketches -> ${file}`)
