// load.mjs: a load generator driven by the real client core (for stream F, dev/load). Every envelope is sealed,
// signed, posted, delivered and verified exactly as in the app and the connector; nothing is faked.
//
//   import { createLoadRoom, runMix } from './load.mjs'
//   const room = await createLoadRoom({ hub_url, humans: 2, agents: 20, fetch })        // fetch: inject test-room headers
//   const stats = await runMix(room, { total: 100_000, rate: 200 /* per second, paced; omit = as fast as possible */, mix: { message: 50, card: 10, revise: 5, answer: 8, status: 20, stroke: 5, attachment: 2 } })
//   await room.close()
//
// stats = { sent, failed, ms, rate, delivered, latency: { p50, p95, p99, max } (ms, send -> verified on the observer), by_kind }
import { foundRoom, joinRoom } from './room.mjs'
import { memoryStorage } from './storage-memory.mjs'

const sleep = ms => new Promise(r => setTimeout(r, ms))
const pct = (sorted, p) => (sorted.length ? sorted[Math.min(sorted.length - 1, Math.floor(p / 100 * sorted.length))] : null)

/** One room: a founding human (the observer), more humans by check code, agents by invite. Memory storage. */
export async function createLoadRoom({ hub_url, humans = 1, agents = 4, found_token = null, fetch = null, client = 'load/1' }) {
  const opts = { fetch, client }
  const { client: observer, recovery_code } = await foundRoom({ hub_url, storage: memoryStorage(), device_name: 'Observer', found_token, ...opts })
  await observer.start()
  const hs = [observer], as = []
  for (let i = 1; i < humans; i++) {
    const inv = await observer.createInvite({ device_role: 'human' })
    const j = joinRoom({ link: inv.link, storage: memoryStorage(), device_name: `Human ${i}`, poll_ms: 50, ...opts })
    const code = await j.check_code
    for (let k = 0; k < 200 && observer.model.invites.get(inv.invite_id).invite_state !== 'confirm_code'; k++) await sleep(25)
    await observer.confirmInvite(inv.invite_id, observer.model.invites.get(inv.invite_id).check_code === code)   // the human compares the emoji
    const c = await j.client
    await c.start()
    hs.push(c)
  }
  for (let i = 0; i < agents; i++) {
    const inv = await observer.createInvite({ device_role: 'agent', label: `Load ${i}` })
    const j = joinRoom({ link: inv.link, storage: memoryStorage(), device_name: `Load agent ${i}`, poll_ms: 50, ...opts })
    const code = await j.check_code
    for (let k = 0; k < 200 && observer.model.invites.get(inv.invite_id).invite_state !== 'confirm_code'; k++) await sleep(25)
    await observer.confirmInvite(inv.invite_id, observer.model.invites.get(inv.invite_id).check_code === code)   // every agent invite asks too
    const c = await j.client
    await c.start()
    as.push(c)
  }
  return {
    observer, humans: hs, agents: as, recovery_code, room_id: observer.model.room.room_id,
    async close() { for (const c of [...hs, ...as]) await c.stop().catch(() => {}) },
  }
}

/**
 * Send `total` envelopes in a weighted mix, spread over the room's devices (agents send cards, revisions, messages,
 * status, attachments; humans answer, send messages, draw). Latency is measured from sealing to the observer verifying it.
 */
export async function runMix(room, { total = 1000, mix = { message: 50, card: 10, revise: 5, answer: 8, status: 20, stroke: 5, attachment: 2 }, concurrency = 16, rate = null, attachment_bytes = 50_000, onProgress = null } = {}) {
  const kinds = Object.entries(mix).filter(([, w]) => w > 0)
  const weight = kinds.reduce((a, [, w]) => a + w, 0)
  const pick = () => { let r = Math.random() * weight; for (const [k, w] of kinds) { if ((r -= w) < 0) return k } return kinds[0][0] }
  const sentAt = new Map(), latencies = [], byKind = {}
  let sent = 0, failed = 0, delivered = 0
  const off = room.observer.on('change', () => {})   // keep the observer live
  // Observe verification on the observer: wrap its record hook once.
  const obs = room.observer
  const orig = obs._record.bind(obs)
  obs._record = (...a) => {
    const rec = orig(...a)
    const t = sentAt.get(rec.envelope_hash)
    if (t != null) { latencies.push(performance.now() - t); sentAt.delete(rec.envelope_hash); delivered++ }
    return rec
  }
  const desk = 'e'.repeat(32)
  const blob = new Uint8Array(attachment_bytes).map((_, i) => i & 0xff)
  const t0 = performance.now()
  let next = 0
  const one = async () => {
    const kind = pick()
    const agent = room.agents[Math.floor(Math.random() * room.agents.length)]
    const human = room.humans[Math.floor(Math.random() * room.humans.length)]
    const own = agent && [...agent.model.cards.values()].filter(c => c.agent_device_id === agent.my_device_id && c.object_state === 'open')
    let r
    switch (kind) {
      case 'card': r = await agent.sendCard({ title: `Load question ${next}`, body: 'Generated by load.mjs.', options: [{ key: 'a', label: 'A' }, { key: 'b', label: 'B' }], urgency: Math.random() < 0.1 ? 'high' : 'normal' }); r = { envelope_hash: agent.localHeads.get(r)?.version_hash }; break
      case 'revise': if (!own.length) return one(); { const id = own[Math.floor(Math.random() * own.length)].object_id; await agent.revise(id, { body: `revised ${next}` }); r = { envelope_hash: agent.localHeads.get(id)?.version_hash } } break
      case 'answer': {
        const open = [...human.model.cards.values()].filter(c => c.object_state === 'open' && c.version_hash && c.options?.length)
        if (!open.length) return one()
        r = await human.answer({ object_id: open[Math.floor(Math.random() * open.length)].object_id, choices: ['a'] })
        break
      }
      case 'status': r = await agent.setStatus({ [`status_line/load${Math.floor(Math.random() * 5)}`]: { label: 'Load', state: 'working', detail: String(next) } }); break
      case 'stroke': r = await human.sendStrokes({ timeline_id: `desk/${desk}`, strokes: [{ points: 'AAAAAAAA', style: { tool: 'pen', color: '#222', size: 2 } }] }); break
      case 'attachment': { const ref = await agent.uploadAttachment(blob, { file_name: 'load.bin', media_type: 'application/octet-stream' }); r = await agent.sendMessage({ text: 'file', attachments: [ref] }); break }
      default: r = Math.random() < 0.7 ? await agent.sendMessage({ text: `load message ${next}` }) : await human.sendMessage({ agent_device_id: agent.my_device_id, text: `human message ${next}` })
    }
    if (r?.envelope_hash) sentAt.set(r.envelope_hash, performance.now())
    byKind[kind] = (byKind[kind] ?? 0) + 1
  }
  const worker = async () => {
    while (next < total) {
      next++
      if (rate) { const due = t0 + (next / rate) * 1000; const wait = due - performance.now(); if (wait > 0) await sleep(wait) }
      try { await one(); sent++ } catch (e) { failed++; if (failed < 5) console.error('[load]', e.code, e.message) }
      if (onProgress && sent % 1000 === 0) onProgress({ sent, failed, delivered })
    }
  }
  await Promise.all(Array.from({ length: concurrency }, worker))
  for (const c of [...room.agents, ...room.humans]) await c.settle({ timeout_ms: 600_000 }).catch(() => {})
  const until = Date.now() + 30_000
  while (sentAt.size && Date.now() < until) await sleep(50)
  obs._record = orig
  off()
  const ms = performance.now() - t0
  latencies.sort((a, b) => a - b)
  return { sent, failed, ms, rate: sent / ms * 1000, delivered, undelivered: sentAt.size,
    latency: { p50: pct(latencies, 50), p95: pct(latencies, 95), p99: pct(latencies, 99), max: latencies.at(-1) ?? null }, by_kind: byKind }
}
