// The named UI states the parity verifier shoots on every target (dev/verify/shoot.mjs). The name is the contract:
// a target adapter (dev/verify/targets/*.mjs) brings its board into the state; `see` says what must be on screen.
// Board content comes from the fixtures (server/fixtures.mjs) plus three demo agents (dev/fake-agent.mjs web, api,
// infra) and a session "Courier" with one approval request; the new app's adapter must create the same content.
export const STATES = [
  { name: 'desk', see: 'Desk of the main desk: sidebar with sessions + counts, Next N, card rows with Choose/answer buttons, knock band' },
  { name: 'desk-test', see: 'Desk "Test": fixture cards of Test Alpha and Test Beta' },
  { name: 'desk-pile-later', see: 'Desk filtered to the snoozed pile' },
  { name: 'desk-pile-done', see: 'Desk filtered to the done pile' },
  { name: 'desk-scrolled-knocks', see: 'Desk scrolled to the bottom: stacks (later, works, done, trash) at the foot' },
  { name: 'menu', see: 'Bell pill menu open: jump field, theme toggle, desks, Agents/Help/Keys, Dev' },
  { name: 'keys-sheet', see: 'The "?" keys sheet' },
  { name: 'jump', see: 'Jump field with results for "Migration"' },
  { name: 'pad', see: 'Scratchpad (key p)' },
  { name: 'pad-cards-hidden', see: 'Desk with cards hidden, only paper left (key w)' },
  { name: 'memo-new', see: 'A new memo note open on the Desk', mutates: true },
  { name: 'rail', see: 'Sidebar folded to a rail (key [)' },
  { name: 'session', see: 'Session Web-Frontend: conversation, cards asked inline, status lines, composer' },
  { name: 'session-permission', see: 'Session Courier: approval request inline, status line' },
  { name: 'session-questions', see: 'Session Test Alpha filtered to its questions' },
  { name: 'session-files', see: 'Files of session Test Beta' },
  { name: 'session-thread', see: 'Session Test Beta conversation (info, code, thread, handback, artifact, files)' },
  { name: 'card-pictures', see: 'Decision with a picture per option, recommended B, arrow pointing from picture to option' },
  { name: 'card-yesno', see: 'Yes/no decision with thumbs and recommended' },
  { name: 'card-long', see: 'Long title + long body + 4 options with short labels' },
  { name: 'card-multiple', see: 'Multiple choice (several answers)' },
  { name: 'card-sections', see: 'Sections question: parts with pictures, required marker' },
  { name: 'card-urgent', see: 'Critical urgency card' },
  { name: 'card-high', see: 'High urgency card with reason' },
  { name: 'card-revised', see: 'A revised card (version marker, what changed)' },
  { name: 'card-marks', see: 'Picture with drawn marks' },
  { name: 'card-snoozed', see: 'Snoozed card' },
  { name: 'card-answered', see: 'Answered card (decided, choice shown, decide again)' },
  { name: 'card-info', see: 'Info card (read, no options)' },
  { name: 'card-code', see: 'Info card with code block, table, list' },
  { name: 'card-thread', see: 'Card with a conversation under it' },
  { name: 'card-handback', see: 'Card handed back (back to you, waiting for revise)' },
  { name: 'card-artifact', see: 'Card with a rich HTML artifact and published assets' },
  { name: 'card-files', see: 'Info card with files attached (log, csv, …)' },
  { name: 'card-permission', see: 'Approval card: Allow / Deny, tool and input preview' },
  { name: 'card-more-menu', see: 'Card "More" menu open (shred, trust, snooze, copy, …)' },
  { name: 'picture', see: 'A picture of a card full page (/p/1) with arrows' },
  { name: 'walk', see: 'Next, please: open questions one after the other' },
  { name: 'agents', see: 'Agents page (Ledger): sessions, drawings, crown, archive, rename' },
  { name: 'help', see: 'Help page' },
  { name: 'card-what-sent', see: 'After pressing What?? on a card: the card says it waits for the agent', mutates: true },
  { name: 'toast-after-answer', see: 'After answering a card: toast with Undo, next card', mutates: true },
]
