#!/usr/bin/env node
// build.mjs: what a machine without a checkout of this repository gets: the connector as ONE file, its checksum, and
// the Trommi plugin for Claude Code with its marketplace.
//
//   node connector/build.mjs [dir]     write them into dir (default app/web/public/gen)
//
//   connector.mjs            connector.mjs + tools.mjs + prompt.md (inlined) + shared/ + @modelcontextprotocol/sdk + zod,
//                            bundled by esbuild (a pinned devDependency) into one ES module
//   connector.mjs.sha256     its SHA-256; the connect script (app/web/public/connect.sh) checks the download against it
//   plugins/marketplace.json, plugins/trommi-<version>.zip
//                            the plugin: .claude-plugin/plugin.json and connector.mjs (that same file)
//
// Nothing of this is committed. The app's build (app/web/dev/build.mjs) calls connectorFiles() and writes the result
// into public/gen/ at deploy time, where the app serves it at https://app.trommi.com/connector.mjs, /connector.mjs.sha256
// and /plugins/… (app/web/worker.js); the dev server (app/web/dev/serve.mjs) serves it from memory.
//
//   claude plugin marketplace add https://app.trommi.com/plugins/marketplace.json
//   claude plugin install trommi@trommi --scope local
//
// The plugin declares the connector as MCP server "trommi", the same server as a channel (claude
// --dangerously-load-development-channels plugin:trommi@trommi still gets live <channel> events), a monitor
// (`node connector.mjs monitor`) that wakes a plain `claude` for every verified board event, and hooks that
// bring a plain `claude`'s permission prompts to the board: PermissionRequest (`node connector.mjs permission`),
// PostToolUse and PostToolUseFailure (`node connector.mjs resolved`: a prompt answered in the terminal leaves the board),
// Notification (`node connector.mjs notice`) and PermissionDenied (`node connector.mjs denied`, one quiet line when
// auto mode blocks a tool call). Its version is the connector's sha256 prefix: a new connector is a new plugin
// version, and `claude plugin update trommi@trommi` (or the marketplace's auto-update) fetches it. The zip is
// deterministic: the same sources give the same bytes.
import fs from 'node:fs'
import path from 'node:path'
import zlib from 'node:zlib'
import crypto from 'node:crypto'
import { fileURLToPath } from 'node:url'
import * as esbuild from 'esbuild'
import { HOOK_TIMEOUT_S, NOTICE_TYPES } from './connector.mjs'

const REPO = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')

/** The single-file connector, as text. */
export function bundle() {
  const r = esbuild.buildSync({
    absWorkingDir: REPO,
    entryPoints: ['connector/connector.mjs'],
    bundle: true, platform: 'node', format: 'esm', target: 'node22',
    write: false, legalComments: 'none', logLevel: 'error', minify: true, keepNames: true,
    // __TROMMI_BUNDLE__: in one file there are no sibling files to hot-reload; any change of it needs a restart.
    // __TROMMI_PROMPT__: prompt.md, which tools.mjs otherwise reads from beside itself.
    define: { __TROMMI_BUNDLE__: 'true', __TROMMI_PROMPT__: JSON.stringify(fs.readFileSync(path.join(REPO, 'connector/prompt.md'), 'utf8')) },
    // CommonJS dependencies of the SDK call require() for Node built-ins; an ES module has none of its own.
    banner: { js: `// Trommi connector, one file. Generated by connector/build.mjs from connector/ and shared/; do not edit.\nimport { createRequire as __trommiRequire } from 'node:module'; const require = __trommiRequire(import.meta.url);` },
  })
  return r.outputFiles[0].text
}

// ---- the plugin and its marketplace ------------------------------------------------------------------------

export const MARKETPLACE = 'trommi'
export const PLUGIN = 'trommi'

export function pluginManifest(version) {
  return {
    name: PLUGIN,
    displayName: 'Trommi',
    version,
    description: 'Connects this Claude Code session to your Trommi board: chat, decision cards and live board events, end-to-end encrypted.',
    author: { name: 'Trommi', url: 'https://trommi.com' },
    homepage: 'https://app.trommi.com',
    mcpServers: { trommi: { command: 'node', args: ['${CLAUDE_PLUGIN_ROOT}/connector.mjs'] } },
    channels: [{ server: 'trommi', displayName: 'Trommi' }],
    hooks: {
      PermissionRequest: [{ hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/connector.mjs" permission', timeout: HOOK_TIMEOUT_S }] }],
      // Answered in the terminal: the call went on, the request leaves the board. Async: never in the tool call's way.
      PostToolUse: [{ hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/connector.mjs" resolved', timeout: 30, async: true }] }],
      PostToolUseFailure: [{ hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/connector.mjs" resolved', timeout: 30, async: true }] }],
      PermissionDenied: [{ hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/connector.mjs" denied', timeout: 30 }] }],
      Notification: [{ matcher: NOTICE_TYPES.join('|'), hooks: [{ type: 'command', command: 'node "${CLAUDE_PLUGIN_ROOT}/connector.mjs" notice', timeout: 60 }] }],
    },
    experimental: {
      monitors: [{ name: 'board', command: 'node "${CLAUDE_PLUGIN_ROOT}/connector.mjs" monitor', description: 'Trommi board events' }],
    },
  }
}

/** The plugin's files: { path: Buffer }. */
export function pluginFiles(connectorText, version) {
  return {
    '.claude-plugin/plugin.json': Buffer.from(JSON.stringify(pluginManifest(version), null, 2) + '\n'),
    'connector.mjs': Buffer.from(connectorText),
  }
}

/** A zip of the files with fixed dates and order: the same input gives the same bytes. */
export function zip(files) {
  const locals = [], centrals = []
  let offset = 0
  for (const name of Object.keys(files).sort()) {
    const data = files[name], packed = zlib.deflateRawSync(data, { level: 9 }), crc = zlib.crc32(data) >>> 0
    const fname = Buffer.from(name)
    const head = Buffer.alloc(30)
    head.writeUInt32LE(0x04034b50, 0); head.writeUInt16LE(20, 4); head.writeUInt16LE(0x0800, 6); head.writeUInt16LE(8, 8)
    head.writeUInt16LE(0, 10); head.writeUInt16LE(0x21, 12) // 1980-01-01 00:00
    head.writeUInt32LE(crc, 14); head.writeUInt32LE(packed.length, 18); head.writeUInt32LE(data.length, 22)
    head.writeUInt16LE(fname.length, 26); head.writeUInt16LE(0, 28)
    const cen = Buffer.alloc(46)
    cen.writeUInt32LE(0x02014b50, 0); cen.writeUInt16LE(0x031e, 4); cen.writeUInt16LE(20, 6); cen.writeUInt16LE(0x0800, 8); cen.writeUInt16LE(8, 10)
    cen.writeUInt16LE(0, 12); cen.writeUInt16LE(0x21, 14)
    cen.writeUInt32LE(crc, 16); cen.writeUInt32LE(packed.length, 20); cen.writeUInt32LE(data.length, 24)
    cen.writeUInt16LE(fname.length, 28); cen.writeUInt32LE((0o100644 << 16) >>> 0, 38); cen.writeUInt32LE(offset, 42)
    locals.push(head, fname, packed)
    centrals.push(cen, fname)
    offset += head.length + fname.length + packed.length
  }
  const cdir = Buffer.concat(centrals)
  const end = Buffer.alloc(22)
  const n = Object.keys(files).length
  end.writeUInt32LE(0x06054b50, 0); end.writeUInt16LE(n, 8); end.writeUInt16LE(n, 10); end.writeUInt32LE(cdir.length, 12); end.writeUInt32LE(offset, 16)
  return Buffer.concat([...locals, cdir, end])
}

export const sha256 = b => crypto.createHash('sha256').update(b).digest('hex')

/** marketplace.json for a plugin source (an archive {url, sha256}, or a relative path for a local test marketplace). */
export function marketplace(source, version) {
  return {
    name: MARKETPLACE,
    owner: { name: 'Trommi', url: 'https://trommi.com' },
    description: 'Trommi for Claude Code',
    plugins: [{ name: PLUGIN, displayName: 'Trommi', version, description: pluginManifest(version).description, source }],
  }
}

/** The marketplace: { file name: Buffer }, served under /plugins/. */
export function marketplaceFiles(connectorText, app = 'https://app.trommi.com') {
  const version = sha256(connectorText).slice(0, 12)
  const archive = zip(pluginFiles(connectorText, version))
  const name = `trommi-${version}.zip`
  const json = marketplace({ source: 'archive', url: `${app}/plugins/${name}`, sha256: sha256(archive) }, version)
  return { 'marketplace.json': Buffer.from(JSON.stringify(json, null, 2) + '\n'), [name]: archive }
}

/** A local marketplace directory with the plugin unpacked (tests; claude plugin marketplace add <dir>). */
export function writeLocalMarketplace(dir, connectorText) {
  const version = sha256(connectorText).slice(0, 12)
  for (const [f, b] of Object.entries(pluginFiles(connectorText, version))) {
    fs.mkdirSync(path.dirname(path.join(dir, 'plugins/trommi', f)), { recursive: true })
    fs.writeFileSync(path.join(dir, 'plugins/trommi', f), b)
  }
  fs.mkdirSync(path.join(dir, '.claude-plugin'), { recursive: true })
  fs.writeFileSync(path.join(dir, '.claude-plugin/marketplace.json'), JSON.stringify(marketplace('./plugins/trommi', version), null, 2) + '\n')
  return { dir, plugin: path.join(dir, 'plugins/trommi'), version }
}

// ---- everything together -------------------------------------------------------------------------------------

/** Everything this build makes: { 'path under gen/': text or Buffer }. */
export function connectorFiles(app = 'https://app.trommi.com') {
  const text = bundle()
  return {
    'connector.mjs': text,
    'connector.mjs.sha256': `${sha256(text)}\n`,
    ...Object.fromEntries(Object.entries(marketplaceFiles(text, app)).map(([f, b]) => [`plugins/${f}`, b])),
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const dir = path.resolve(process.argv[2] ?? path.join(REPO, 'app/web/public/gen'))
  const files = connectorFiles()
  fs.rmSync(path.join(dir, 'plugins'), { recursive: true, force: true })
  for (const [f, c] of Object.entries(files)) { fs.mkdirSync(path.dirname(path.join(dir, f)), { recursive: true }); fs.writeFileSync(path.join(dir, f), c) }
  console.log(`wrote ${Object.keys(files).join(', ')} into ${path.relative(process.cwd(), dir) || '.'} (connector ${(files['connector.mjs'].length / 1024).toFixed(0)} KiB, sha256 ${files['connector.mjs.sha256'].slice(0, 12)})`)
}
